version: '3'
services:
  db:
    container_name: db-poc-middleware
    image: mysql:5.7
    command: mysqld --user=root --verbose
    volumes:
      - ./db/schema_new.sql:/docker-entrypoint-initdb.d/schema_new.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=poc_middleware
    ports:
      - "3306:3306"
  mq:
    container_name: mq-poc-middleware
    image: webcenter/activemq:5.14.3
    environment:
      - ACTIVEMQ_NAME=localhost
      - ACTIVEMQ_STATIC_QUEUES=TRAMITES
    ports:
      - "61616:61616"
      - "8161:8161"
  middleware:
    container_name: fuse-middleware
    build: esb/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - ACTIVEMQ_NAME=localhost
      - ACTIVEMQ_STATIC_QUEUES=TRAMITES
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    depends_on:
      - db
      - mq
    links:
      - db
      - mq
  
